### PR TITLE
add network timeouts and make post consistent

### PR DESCRIPTION
**Pull request by atimgraves**
I have been having intermittent problems connecting to my battery which has resulted in the data coordinator crashing out with max retries being exceeded.
This update adds connection timeout params to the requests library calls which results in a catchable exception instead of an error. There are  set in the cost.py file and provide for a longer call when getting the oauth token, but then a relatively short timeout for data accesses to stop long blocking calls delaying other service updates

### CODE REVIEW

**Comment by weltmeyer** [comment]
Released. had to fix the REQUEST_TIMEOUT const.

**Comment by atimgraves** [comment]
Opps, what did I do wrong with it ?

**Comment by weltmeyer** [comment]
Seems like the request just want a regular tuple instead of any special type there.. i could not run the tests without making it a normale tuple.

It expects timeout = (3, 5) instead of timeout = Timeout(3, 5)

**Comment by atimgraves** [comment]
Interesting, it worked fine in my environment, wonder what's different. But it works now so let's not do anything to break it ! (As a Java guy I'm finding Python a little different :-( )
I'll start testing my changes to the HA sonnen batterie module soon

**Comment by weltmeyer** [comment]
As a dotNet guy.. i consent

**Comment by atimgraves** [comment]
Hi Jan
Would you be OK if I moved the SonnenBatterieMonitor class from sensores.py  into a different file ?
I have another class that it references, but also needs to reference it and this is the only way I can come up with that doesn't result in a load failure due to circular imports
Thanks

**Comment by weltmeyer** [comment]
There is no more SonnenBatterieMonitor after the latest updates, only Sensor and SonnenBatterieCoordinator are left, 
SonnenBatterieCoordinator replaced Monitor and the update gets handled by homeassistant.

But i am okay to move it to its own file.

**Comment by atimgraves** [comment]
Ah, I need to update my local repo before doing anything else then.
My updated code has been running OK for a few days with no problems (and
recovering from the network timeouts I've been having with my home
network). I'll merge my changes into your latest version locally and run it
via HASS then share it for you to try before I do a PR
Thanks

**Pull request merged**
